[en]
languageName = "English"
weight =  1
[jp]
languageName = "日本語"
weight =  2
[pt]
languageName = "Português"
weight =  3
[es]
languageName = "Español"
weight =  4
[ru]
languageName = "Русский"
weight =  5
[tr]
languageName = "Türkçe"
weight =  6
[de]
languageName = "German"
weight =  7