
[[hispano2020]]
    name = "Conferencista"
    url = "/2020/hispano/#speakers"
    weight = 2

[[hispano2020]]
    name = "Asistir"
    weight = 3

[[hispano2020]]
    name = "CÃ³digo de Conducta"
    url = "/2020/hispano/code-of-conduct/"
    weight = 1
    parent = "Asistir"

[[hispano2020]]
    name = "Acuerdo del Conferencista"
    url = "/2020/hispano/speaker-agreement/"
    weight = 2
    parent = "Asistir"
    