baseurl = "https://jakartaone.org/"
#baseurl = "https://jakartaee.github.io/jakartaone.org/"
DefaultContentLanguage = "en"
title = "JakartaOne Live | Jakarta EE Software | Cloud Native"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = ["taxonomy", "taxonomyTerm"]
themesDir = "node_modules/"

[languages]
  [languages.en]
    languageName = "English"
    weight =  1
  [languages.jp]
    languageName = "日本語"
    weight =  2
  [languages.pt]
    languageName = "Português"
    weight =  3
  [languages.es]
    languageName = "Español"
    weight =  4
  [languages.ru]
    languageName = "русский язык"
    weight =  5

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "JakartaOne Live is a one day virtual conference for developers and technical business leaders that brings insights into the current state and future of Jakarta EE and related technologies focused on developing cloud-native Java applications."
  subtitle = "JakartaOne Live | Jakarta EE Software | Cloud Native"
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["JakartaOne", "JakartaOne Live", "Jakarta EE software", "Java EE", "cloud", "microservices", "enterprise", "open source", "innovation"]
  logo = "images/jakartaone_livestream_wht_full-06.svg"
  logo_width = 250
  header_left_classes = "col-xs-8"
  main_menu_wrapper_classes = "col-sm-16"
  styles = "css/styles.css"
  favicon = "images/jakarta/favicon.ico"
  share_img = "images/jakarta/jakarta_ee_400x400.png"
#  gcse = "011805775785170369411:p3ec0igo0qq"
  subtheme = "jakarta"
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
  featured_content_publish_target = "jakarta_ee"
# show_events = true
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[languages.en.menu.2019]]
    name = "Plan of the day"
    url = "/2019/#plan-of-the-day"
    weight = 1
    
[[languages.en.menu.2019]]
    name = "Program committee"
    url = "/2019/program-committee/"
    weight = 2

[[languages.en.menu.2019]]
    name = "Attend"
    weight = 3

[[languages.en.menu.2019]]
    name = "Code of Conduct"
    url = "/2019/code-of-conduct/"
    weight = 1
    parent = "Attend"
    
[[languages.en.menu.2019]]
    name = "Speaker Agreement"
    url = "/speaker-agreement/"
    weight = 2
    parent = "Attend"

#### 2020 menus ####
[[languages.en.menu.2020]]
    name = "Schedule"
    url = "/2020/#plan-of-the-day"
    weight = 1
    
[[languages.en.menu.2020]]
    name = "Program committee"
    url = "/2020/program-committee/"
    weight = 2

[[languages.en.menu.2020]]
    name = "Attend"
    weight = 3

[[languages.en.menu.2020]]
    name = "Code of Conduct"
    url = "/2020/code-of-conduct/"
    weight = 1
    parent = "Attend"
    
[[languages.en.menu.2020]]
    name = "Speaker Agreement"
    url = "/speaker-agreement/"
    weight = 2
    parent = "Attend"

#### 2020 menus end ####


[[languages.en.menu.japan2020]]
    name = "Plan of the day"
    url = "/2020/japan/#plan-of-the-day"
    weight = 1

[[languages.en.menu.japan2020]]
    name = "Program committee"
    url = "/2020/japan/program-committee/"
    weight = 2

[[languages.en.menu.japan2020]]
    name = "Attend"
    weight = 3

[[languages.en.menu.japan2020]]
    name = "Code of Conduct"
    url = "/2020/japan/code-of-conduct/"
    weight = 1
    parent = "Attend"

[[languages.en.menu.japan2020]]
    name = "Speaker Agreement"
    url = "/speaker-agreement/"
    weight = 2
    parent = "Attend"

[[languages.jp.menu.japan2020]]
    name = "タイムテーブル"
    url = "/2020/japan/#plan-of-the-day"
    weight = 1

[[languages.jp.menu.japan2020]]
    name = "プログラム委員会"
    url = "/2020/japan/program-committee/"
    weight = 2

[[languages.jp.menu.japan2020]]
    name = "行動指針"
    weight = 3

[[languages.jp.menu.japan2020]]
    name = "行動規範"
    url = "/2020/japan/code-of-conduct/"
    weight = 1
    parent = "行動指針"

[[languages.jp.menu.japan2020]]
    name = "Speaker Agreement"
    url = "/speaker-agreement/"
    weight = 2
    parent = "行動指針"

[[languages.en.menu.cn4j2020]]
    name = "Event Details"
    url = "/2020/cn4j/#plan-of-the-day"
    weight = 1
    
[[languages.en.menu.cn4j2020]]
    name = "Speakers"
    url = "/2020/cn4j/#speakers"
    weight = 2

[[languages.en.menu.cn4j2020]]
    name = "Attend"
    weight = 3

[[languages.en.menu.cn4j2020]]
    name = "Code of Conduct"
    url = "/2020/cn4j/code-of-conduct/"
    weight = 1
    parent = "Attend"
    
[[languages.en.menu.cn4j2020]]
    name = "Speaker Agreement"
    url = "/2020/cn4j/speaker-agreement/"
    weight = 2
    parent = "Attend"

[[languages.en.menu.brazil2020]]
    name = "Event Details"
    url = "/2020/brazil/#plan-of-the-day"
    weight = 1
    
[[languages.en.menu.brazil2020]]
    name = "Speakers"
    url = "/2020/brazil/#speakers"
    weight = 2

[[languages.en.menu.brazil2020]]
    name = "Attend"
    weight = 3

[[languages.en.menu.brazil2020]]
    name = "Code of Conduct"
    url = "/2020/brazil/code-of-conduct/"
    weight = 1
    parent = "Attend"
    
[[languages.en.menu.brazil2020]]
    name = "Speaker Agreement"
    url = "/2020/brazil/speaker-agreement/"
    weight = 2
    parent = "Attend"

[[languages.pt.menu.brazil2020]]
    name = "Detalhes do Evento"
    url = "/2020/brazil/#plan-of-the-day"
    weight = 1
    
[[languages.pt.menu.brazil2020]]
    name = "Palestrantes"
    url = "/2020/brazil/#speakers"
    weight = 2

[[languages.pt.menu.brazil2020]]
    name = "Participe"
    weight = 3

[[languages.pt.menu.brazil2020]]
    name = "Código de Conduta"
    url = "/2020/brazil/code-of-conduct/"
    weight = 1
    parent = "Participe"
    
[[languages.pt.menu.brazil2020]]
    name = "Termo de Compromisso"
    url = "/2020/brazil/speaker-agreement/"
    weight = 2
    parent = "Participe"

[[languages.en.menu.hispano2020]]
    name = "Speakers"
    url = "/2020/hispano/#speakers"
    weight = 2

[[languages.en.menu.hispano2020]]
    name = "Attend"
    weight = 3

[[languages.en.menu.hispano2020]]
    name = "Code of Conduct"
    url = "/2020/hispano/code-of-conduct/"
    weight = 1
    parent = "Attend"

[[languages.en.menu.hispano2020]]
    name = "Speaker Agreement"
    url = "/2020/hispano/speaker-agreement/"
    weight = 2
    parent = "Attend"

[[languages.es.menu.hispano2020]]
    name = "Conferencista"
    url = "/2020/hispano/#speakers"
    weight = 2

[[languages.es.menu.hispano2020]]
    name = "Asistir"
    weight = 3

[[languages.es.menu.hispano2020]]
    name = "Código de Conducta"
    url = "/2020/hispano/code-of-conduct/"
    weight = 1
    parent = "Asistir"

[[languages.es.menu.hispano2020]]
    name = "Acuerdo del Conferencista"
    url = "/2020/hispano/speaker-agreement/"
    weight = 2
    parent = "Asistir"
    